from __future__ import annotations

"""Canonical score-time recovery for scanned PDF scores.

The tone-metric algorithm must operate in musical time, not in PDF geometry.  This
module reads Audiveris' saved notation graph and builds a measure-local metric grid
first.  Recognized note/rest columns are then assigned to that grid.  PDF x/y is kept
only as provenance for the later drawing stage.

Important rules implemented here:
- augmentation dots extend duration but never create attacks;
- tie continuations occupy a score position but do not create attacks;
- rests occupy score time but do not create attacks;
- an attack in any other voice at the same position still creates a global hit;
- simultaneous/near-coincident noteheads are one physical attack column;
- Audiveris BEGIN slot times are useful constraints, but contradictory ones cannot
  reorder the printed score.  A maximum feasible monotonic subset is used as anchors;
- missing semantic slots are filled on an exact rational metric lattice.  Geometry is
  used only to choose among positions already generated by that lattice.
"""

from collections import Counter, defaultdict
from dataclasses import asdict, dataclass
from fractions import Fraction
from io import BytesIO
from math import gcd
from pathlib import Path, PurePosixPath
from zipfile import ZipFile
import re

import numpy as np
from lxml import etree
from PIL import Image

from .models import Hit, MeasureInfo


def _local(tag: str) -> str:
    return tag.rsplit("}", 1)[-1].lower()


def _frac(value) -> Fraction | None:
    try:
        return Fraction(str(value))
    except Exception:
        return None


def _int(value, default=None):
    try:
        return int(float(str(value)))
    except Exception:
        return default


def _bounds(el):
    b = next((c for c in el if _local(c.tag) == "bounds"), None)
    if b is None:
        return None
    try:
        return tuple(float(b.get(k)) for k in ("x", "y", "w", "h"))
    except Exception:
        return None


def _median_points(stem_el):
    med = next((c for c in stem_el if _local(c.tag) == "median"), None)
    if med is None:
        return None
    pts = [c for c in med if _local(c.tag) in {"p1", "p2"}]
    if len(pts) < 2:
        return None
    try:
        return (
            (float(pts[0].get("x")), float(pts[0].get("y"))),
            (float(pts[1].get("x")), float(pts[1].get("y"))),
        )
    except Exception:
        return None


def _page_image(zf: ZipFile, sheet_member: str):
    folder = str(PurePosixPath(sheet_member).parent)
    for name in ("BINARY.png", "GRAY.png"):
        member = f"{folder}/{name}"
        if member in zf.namelist():
            im = Image.open(BytesIO(zf.read(member))).convert("L")
            im.load()
            return im
    return None


def _sheet_no(member: str) -> int:
    m = re.search(r"sheet#(\d+)", member, re.I)
    return int(m.group(1)) if m else 10**9


def _corridor_fraction(arr: np.ndarray, p1, p2, offset: float, half: int = 2) -> float:
    x1, y1 = p1
    x2, y2 = p2
    if abs(x2 - x1) < 6:
        return 0.0
    xa = int(min(x1, x2)) + 3
    xb = int(max(x1, x2)) - 3
    if xb <= xa:
        return 0.0
    dark = total = 0
    for x in range(xa, xb + 1):
        t = (x - x1) / (x2 - x1)
        y = y1 + t * (y2 - y1) + offset
        yi = int(round(y))
        y0 = max(0, yi - half)
        y1i = min(arr.shape[0], yi + half + 1)
        col = arr[y0:y1i, x]
        dark += int(np.count_nonzero(col < 128))
        total += int(col.size)
    return dark / total if total else 0.0


def _beam_band_count(arr: np.ndarray, a: dict, b: dict, interline: float) -> int:
    """Supplement missing semantic beam relations from the saved OMR raster.

    Stem direction is used only for local beam recognition, never for voice/timing.
    """
    if not a.get("distal") or not b.get("distal"):
        return 0
    if a.get("direction") != b.get("direction"):
        return 0
    p1, p2 = a["distal"], b["distal"]
    if abs(p2[0] - p1[0]) > max(140.0, interline * 7.0):
        return 0
    inward = 1.0 if a["direction"] == "up" else -1.0
    offsets = [inward * x for x in np.arange(-3.0, max(9.0, interline * 1.55), 2.0)]
    vals = [_corridor_fraction(arr, p1, p2, off, half=2) for off in offsets]
    active = [v >= 0.47 for v in vals]
    clusters = []
    i = 0
    while i < len(active):
        if not active[i]:
            i += 1
            continue
        j = i
        peak = vals[i]
        while j + 1 < len(active) and active[j + 1]:
            j += 1
            peak = max(peak, vals[j])
        if peak >= 0.58 and (j - i + 1) >= 2:
            clusters.append((i, j, peak))
        i = j + 1
    return min(4, len(clusters))


def _head_kind(head_shapes: list[str]) -> str:
    text = " ".join(head_shapes).upper()
    if "WHOLE" in text:
        return "whole"
    if "VOID" in text or "HALF" in text:
        return "half"
    return "black"


def _rest_duration(shape: str) -> Fraction | None:
    s = (shape or "").upper()
    if "LONG_REST" in s:
        return Fraction(8)
    if "WHOLE_REST" in s:
        return Fraction(4)
    if "HALF_REST" in s:
        return Fraction(2)
    if "QUARTER_REST" in s:
        return Fraction(1)
    if "EIGHTH_REST" in s:
        return Fraction(1, 2)
    m = re.search(r"(?:ONE_)?(\d+)(?:TH|ND|ST|RD)_REST", s)
    if m:
        den = int(m.group(1))
        if den > 0:
            return Fraction(4, den)
    return None


def _dot_multiplier(count: int) -> Fraction:
    out = Fraction(1)
    add = Fraction(1, 2)
    for _ in range(max(0, count)):
        out += add
        add /= 2
    return out


def _fraction_gcd(values: list[Fraction]) -> Fraction:
    vals = [v for v in values if v is not None and v > 0]
    if not vals:
        return Fraction(1, 2)
    den = 1
    for v in vals:
        den = den * v.denominator // gcd(den, v.denominator)
    nums = [int(v * den) for v in vals]
    g = nums[0]
    for n in nums[1:]:
        g = gcd(g, n)
    return Fraction(g, den)


@dataclass
class CanonicalColumn:
    global_measure_index: int
    page_index: int
    system_index: int
    stack_index_in_system: int
    x_abs: float
    y_abs: float
    onset_quarter: Fraction
    duration_quarter: Fraction
    attack: bool
    rest: bool
    tie_continuation_only: bool
    chord_ids: list[str]
    assigned_begin_times: list[Fraction]
    notation_events: list[dict]
    timing_source: str
    confidence: float

    def row(self) -> dict:
        row = asdict(self)
        row["onset_quarter"] = str(self.onset_quarter)
        row["duration_quarter"] = str(self.duration_quarter)
        row["assigned_begin_times"] = [str(x) for x in self.assigned_begin_times]
        return row


def _choose_feasible_semantic_anchors(columns: list[dict], quantum: Fraction, full: Fraction) -> dict[int, int]:
    """Choose a maximum-support monotonic subset of Audiveris BEGIN times.

    Feasibility includes enough unused metric-grid positions for every intervening
    physical column.  This is the key safeguard against contradictory OMR slot data.
    """
    n = len(columns)
    units = int(full / quantum)
    candidates: list[tuple[int, int, int]] = []
    for i, col in enumerate(columns):
        counts = Counter(col.get("assigned_begin_times", []))
        for t, support in counts.items():
            if t < 0 or t >= full:
                continue
            ratio = t / quantum
            if ratio.denominator != 1:
                continue
            j = int(ratio)
            if j < i or units - 1 - j < n - 1 - i:
                continue
            candidates.append((i, j, int(support)))

    # The leftmost recognized event/rest column defines the measure origin.  If OMR
    # failed to provide it semantically we still place it on the pre-existing t=0 grid.
    anchors: dict[int, int] = {0: 0}
    if n <= 1:
        return anchors

    # Weighted longest feasible path.  Support dominates anchor count.
    candidates = [(i, j, w) for i, j, w in candidates if i > 0 and j > 0]
    dp: list[tuple[int, int, int, int] | None] = [None] * len(candidates)
    parent = [-1] * len(candidates)
    for a, (i, j, w) in enumerate(candidates):
        if j < i:  # must leave one grid position per preceding column
            continue
        best = (w, 1, -j, -i)
        best_parent = -1
        for b in range(a):
            if dp[b] is None:
                continue
            pi, pj, _pw = candidates[b]
            if i <= pi or j - pj < i - pi:
                continue
            score = (dp[b][0] + w, dp[b][1] + 1, -j, -i)
            if score > best:
                best = score
                best_parent = b
        dp[a] = best
        parent[a] = best_parent

    if not dp:
        return anchors
    valid = [i for i, x in enumerate(dp) if x is not None]
    if not valid:
        return anchors
    k = max(valid, key=lambda idx: dp[idx])
    chain = []
    while k >= 0:
        chain.append(candidates[k])
        k = parent[k]
    for i, j, _w in reversed(chain):
        anchors[i] = j
    return anchors


def _fill_metric_positions(columns: list[dict], anchors: dict[int, int], quantum: Fraction, full: Fraction) -> tuple[list[int], dict]:
    n = len(columns)
    units = int(full / quantum)
    if n == 0:
        return [], {}
    anchors = dict(anchors)
    anchors[0] = 0

    # Estimate pixels per grid unit from trusted anchor pairs.
    ordered = sorted(anchors.items())
    scales = []
    for (i0, j0), (i1, j1) in zip(ordered, ordered[1:]):
        if j1 > j0 and columns[i1]["x_abs"] > columns[i0]["x_abs"]:
            scales.append((columns[i1]["x_abs"] - columns[i0]["x_abs"]) / (j1 - j0))
    if scales:
        px_per_unit = sorted(scales)[len(scales) // 2]
    elif n > 1:
        px_per_unit = max(1.0, (columns[-1]["x_abs"] - columns[0]["x_abs"]) / max(1, n - 1))
    else:
        px_per_unit = 1.0

    # If there is no semantic anchor at the right, extrapolate only as far as the
    # notation spacing suggests; never beyond the measure grid.
    last_i, last_j = max(anchors.items())
    if last_i < n - 1:
        dx = columns[-1]["x_abs"] - columns[last_i]["x_abs"]
        estimated = last_j + max(n - 1 - last_i, int(round(dx / max(px_per_unit, 1e-6))))
        last_target = min(units - 1, max(last_j + (n - 1 - last_i), estimated))
        anchors[n - 1] = last_target

    js = [-1] * n
    for i, j in anchors.items():
        js[i] = j

    ordered = sorted(anchors.items())
    for (i0, j0), (i1, j1) in zip(ordered, ordered[1:]):
        count = i1 - i0
        if count <= 1:
            continue
        x0 = columns[i0]["x_abs"]
        x1 = columns[i1]["x_abs"]
        prev = j0
        for i in range(i0 + 1, i1):
            remaining = i1 - i
            if x1 > x0:
                ideal = j0 + (j1 - j0) * ((columns[i]["x_abs"] - x0) / (x1 - x0))
            else:
                ideal = j0 + (j1 - j0) * ((i - i0) / count)
            lo = prev + 1
            hi = j1 - remaining
            j = max(lo, min(hi, int(round(ideal))))
            js[i] = j
            prev = j

    # Defensive fill (should only occur with a one-column measure).
    prev = -1
    for i, j in enumerate(js):
        if j < 0:
            j = min(units - 1, prev + 1)
            js[i] = j
        prev = j

    semantic = _choose_feasible_semantic_anchors(columns, quantum, full)
    audit = {
        "quantum_quarter": str(quantum),
        "grid_units_per_measure": units,
        "semantic_anchor_count": len(semantic),
        "semantic_anchor_indices": {str(i): int(j) for i, j in sorted(semantic.items())},
        "all_timing_anchor_indices": {str(i): int(j) for i, j in sorted(anchors.items())},
        "px_per_grid_unit": float(px_per_unit),
    }
    return js, audit



class CanonicalFrameworkError(RuntimeError):
    """Raised when OMR and MusicXML cannot be reconciled without guessing."""


def _omr_measure_stack_count(omr_path: str | Path) -> int:
    path = Path(omr_path)
    count = 0
    with ZipFile(path, "r") as zf:
        members = sorted(
            [n for n in zf.namelist() if re.search(r"sheet#\d+/sheet#\d+\.xml$", n, re.I)],
            key=_sheet_no,
        )
        for member in members:
            root = etree.fromstring(zf.read(member))
            for system in [e for e in root.iter() if _local(e.tag) == "system"]:
                count += sum(1 for child in system if _local(child.tag) == "stack")
    return count


def _numeric_measure_number(value) -> int | None:
    m = re.fullmatch(r"\s*(-?\d+)\s*", str(value or ""))
    return int(m.group(1)) if m else None


def _reconcile_measure_framework_with_omr(omr_path, measures, symbolic_hits=None) -> tuple[dict, list[str]]:
    """Expand sparse MusicXML measure metadata to the finalized OMR stack order.

    Audiveris can retain all physical measure stacks in the finalized OMR while
    omitting individual measures from MusicXML.  When the surviving MusicXML
    numbers unambiguously span the complete OMR score, restore only the missing
    measure shells and keep known MusicXML measures at their true physical ordinal.
    Meter is inherited across a gap only when both known neighbors agree.
    """
    original = list(measures)
    symbolic_hits = list(symbolic_hits or [])
    omr_count = _omr_measure_stack_count(omr_path)
    info = {
        "musicxml_measure_count": len(original),
        "omr_measure_stack_count": omr_count,
        "framework_measure_count": len(original),
        "framework_reconciled": False,
        "synthesized_measure_count": 0,
        "synthesized_measure_numbers": [],
        "framework_alignment": "musicxml-sequential",
    }
    warnings: list[str] = []
    if omr_count <= len(original):
        if omr_count < len(original):
            warnings.append(
                f"Finalized OMR contains {omr_count} measure stacks but MusicXML contains {len(original)} measures; no OMR expansion was required."
            )
        return info, warnings

    numbers = [_numeric_measure_number(m.number) for m in original]
    if not original or any(n is None for n in numbers):
        raise CanonicalFrameworkError(
            f"Finalized OMR contains {omr_count} measure stacks but MusicXML contains only {len(original)} measures, and MusicXML numbering is not a complete numeric ordinal map."
        )
    nums = [int(n) for n in numbers]
    if any(b <= a for a, b in zip(nums, nums[1:])):
        raise CanonicalFrameworkError(
            "Sparse MusicXML measure numbers are not strictly increasing, so omitted OMR measures cannot be restored without guessing."
        )
    base_number = nums[0]
    target_indices = [n - base_number for n in nums]
    if target_indices[0] != 0 or target_indices[-1] != omr_count - 1:
        raise CanonicalFrameworkError(
            f"MusicXML measure numbering spans {nums[0]}–{nums[-1]}, which does not unambiguously cover all {omr_count} finalized OMR measure stacks."
        )
    if len(set(target_indices)) != len(target_indices) or any(i < 0 or i >= omr_count for i in target_indices):
        raise CanonicalFrameworkError(
            "MusicXML measure numbers cannot be mapped one-to-one onto the finalized OMR measure stacks."
        )

    expanded: list[MeasureInfo | None] = [None] * omr_count
    old_to_new: dict[int, int] = {}
    for old_index, (measure, target_index) in enumerate(zip(original, target_indices)):
        expanded[target_index] = measure
        old_to_new[old_index] = target_index

    missing_indices = [i for i, measure in enumerate(expanded) if measure is None]
    for i in missing_indices:
        prev = next((expanded[j] for j in range(i - 1, -1, -1) if expanded[j] is not None), None)
        nxt = next((expanded[j] for j in range(i + 1, omr_count) if expanded[j] is not None), None)
        if prev is None or nxt is None:
            raise CanonicalFrameworkError(
                f"OMR measure {base_number + i} is missing from MusicXML at an unbounded score edge; its meter cannot be restored safely."
            )
        prev_meter = (int(prev.numerator), int(prev.denominator))
        next_meter = (int(nxt.numerator), int(nxt.denominator))
        if prev_meter != next_meter:
            raise CanonicalFrameworkError(
                f"OMR measure {base_number + i} is missing from MusicXML between conflicting meters {prev_meter[0]}/{prev_meter[1]} and {next_meter[0]}/{next_meter[1]}; analysis will not guess the meter change."
            )
        numerator, denominator = prev_meter
        full = Fraction(numerator * 4, denominator)
        expanded[i] = MeasureInfo(
            index=i,
            number=str(base_number + i),
            start=Fraction(0),
            full_duration=full,
            actual_duration=full,
            pickup_shift=Fraction(0),
            numerator=numerator,
            denominator=denominator,
            implicit=False,
        )

    restored = [m for m in expanded if m is not None]
    if len(restored) != omr_count:
        raise CanonicalFrameworkError(
            "Internal framework reconciliation failed to restore every finalized OMR measure stack."
        )

    start = Fraction(0)
    for i, measure in enumerate(restored):
        measure.index = i
        measure.start = start
        start += measure.full_duration

    for hit in symbolic_hits:
        old_index = int(hit.measure_index)
        if old_index not in old_to_new:
            raise CanonicalFrameworkError(
                f"Symbolic hit references unknown MusicXML measure index {old_index} during OMR reconciliation."
            )
        new_index = old_to_new[old_index]
        measure = restored[new_index]
        hit.measure_index = new_index
        hit.onset = measure.start + hit.offset_in_measure
        for src in hit.sources:
            src.measure_index = new_index
            src.onset = measure.start + src.offset_in_measure

    measures[:] = restored
    synthesized_numbers = [str(base_number + i) for i in missing_indices]
    info.update({
        "framework_measure_count": len(restored),
        "framework_reconciled": True,
        "synthesized_measure_count": len(missing_indices),
        "synthesized_measure_numbers": synthesized_numbers,
        "framework_alignment": "finalized-omr-stack-order+musicxml-number-anchors",
    })
    warnings.append(
        f"Restored {len(missing_indices)} MusicXML-omitted measure shells from the finalized OMR stack order; no meter was guessed across a conflicting change."
    )
    return info, warnings

def recover_canonical_columns(omr_path: str | Path, measures, cluster_tolerance_px: float = 12.0) -> tuple[list[CanonicalColumn], dict]:
    path = Path(omr_path)
    out: list[CanonicalColumn] = []
    meta = {
        "available": False,
        "warnings": [],
        "measures": [],
        "page_dimensions": {},
        "architecture": "metric-grid-first/notation-semantics/global-attack-map",
    }
    if not path.exists():
        meta["warnings"].append("Saved OMR project not found.")
        return out, meta

    global_measure = 0
    page_index = 0
    augmentation_relation_count = 0
    with ZipFile(path, "r") as zf:
        members = sorted(
            [n for n in zf.namelist() if re.search(r"sheet#\d+/sheet#\d+\.xml$", n, re.I)],
            key=_sheet_no,
        )
        for member in members:
            root = etree.fromstring(zf.read(member))
            image = _page_image(zf, member)
            arr = np.asarray(image) if image is not None else None
            if image is not None:
                meta["page_dimensions"][str(page_index)] = [int(image.width), int(image.height)]
            interline = 19.0
            il = next((e for e in root.iter() if _local(e.tag) == "interline"), None)
            if il is not None:
                interline = float(il.get("main") or il.get("min") or interline)

            systems = [e for e in root.iter() if _local(e.tag) == "system"]
            for system_index, system in enumerate(systems):
                objs = {str(e.get("id")): e for e in system.iter() if e.get("id") is not None}
                rels = []
                for rel in system.iter():
                    if _local(rel.tag) != "relation":
                        continue
                    typ = next((_local(c.tag) for c in rel if isinstance(c.tag, str)), "")
                    rels.append((str(rel.get("source") or ""), str(rel.get("target") or ""), typ, rel))

                chord_members = defaultdict(list)
                chord_stem = {}
                stem_beams = defaultdict(set)
                stem_flags = defaultdict(list)
                dotted_heads = Counter()
                tie_right_heads = set()
                for source, target, typ, rel in rels:
                    if typ == "containment" and source in objs and target in objs:
                        if _local(objs[source].tag) in {"head-chord", "rest-chord"}:
                            chord_members[source].append(target)
                    elif typ == "chord-stem":
                        chord_stem[source] = target
                    elif typ == "beam-stem":
                        stem_beams[target].add(source)
                    elif typ == "flag-stem":
                        stem_flags[target].append(source)
                    elif typ == "augmentation" and source in objs and target in objs:
                        augmentation_relation_count += 1
                        if _local(objs[source].tag) == "head":
                            dotted_heads[source] += 1
                        elif _local(objs[target].tag) == "head":
                            dotted_heads[target] += 1
                    elif typ == "slur-head" and source in objs and target in objs:
                        slur = objs[source]
                        if _local(slur.tag) == "slur" and (slur.get("tie") or "").lower() == "true":
                            spec = next((c for c in rel if _local(c.tag) == "slur-head"), None)
                            if spec is not None and (spec.get("side") or "").upper() == "RIGHT":
                                tie_right_heads.add(target)

                stacks = [e for e in system if _local(e.tag) == "stack"]
                parts = [e for e in system if _local(e.tag) == "part"]
                part_measures = [[m for m in p if _local(m.tag) == "measure"] for p in parts]

                for stack_index, stack in enumerate(stacks):
                    if global_measure >= len(measures):
                        meta["warnings"].append("OMR contains more measure stacks than the canonical MusicXML framework.")
                        break
                    measure = measures[global_measure]
                    full = measure.full_duration
                    left = float(stack.get("left") or 0.0)
                    right = float(stack.get("right") or left + 1.0)
                    slot_time = {}
                    for sl in stack:
                        if _local(sl.tag) == "slot":
                            key = str(sl.get("id") or "")
                            t = _frac(sl.get("time-offset"))
                            if key and t is not None:
                                slot_time[key] = t * 4

                    measure_nodes = [ms[stack_index] for ms in part_measures if stack_index < len(ms)]
                    head_chords: list[str] = []
                    rest_chords: list[str] = []
                    begin_times = defaultdict(list)
                    continue_times = defaultdict(list)
                    for meas in measure_nodes:
                        for tag, bucket in (("head-chords", head_chords), ("rest-chords", rest_chords)):
                            el = next((c for c in meas if _local(c.tag) == tag), None)
                            if el is not None and el.text:
                                bucket.extend(el.text.split())
                        for voice in [c for c in meas if _local(c.tag) == "voice"]:
                            slots_el = next((c for c in voice if _local(c.tag) == "slots"), None)
                            if slots_el is None:
                                continue
                            for entry in [c for c in slots_el if _local(c.tag) == "entry"]:
                                key = next((c for c in entry if _local(c.tag) == "key"), None)
                                val = next((c for c in entry if _local(c.tag) == "value"), None)
                                if key is None or val is None or not key.text:
                                    continue
                                cid = val.get("chord")
                                t = slot_time.get(key.text.strip())
                                if not cid or t is None:
                                    continue
                                if (val.get("status") or "").upper() == "BEGIN":
                                    begin_times[str(cid)].append(t)
                                else:
                                    continue_times[str(cid)].append(t)

                    head_chords = list(dict.fromkeys(head_chords))
                    rest_chords = list(dict.fromkeys(rest_chords))
                    infos = []
                    # First pass: geometry, semantic beams/flags, tie/dot identity.
                    for cid in head_chords:
                        cel = objs.get(cid)
                        cb = _bounds(cel) if cel is not None else None
                        if cel is None or cb is None:
                            continue
                        x, y, w, h = cb
                        members = [objs[m] for m in chord_members.get(cid, []) if m in objs]
                        heads = [m for m in members if _local(m.tag) == "head"]
                        hb = [_bounds(hd) for hd in heads]
                        hb = [b for b in hb if b]
                        hcx = [a + c / 2 for a, b, c, d in hb]
                        hcy = [b + d / 2 for a, b, c, d in hb]
                        # Horizontal registration uses the physical chord box center.  We do
                        # not average multiple independent attack columns; notehead y-centers
                        # are used only to keep the vertical guide near the sounding heads.
                        center = (x + w / 2, sum(hcy) / len(hcy)) if hcy else (x + w / 2, y + h / 2)
                        stem_id = chord_stem.get(cid)
                        stem = objs.get(stem_id) if stem_id else None
                        median = _median_points(stem) if stem is not None else None
                        direction = "none"
                        distal = None
                        if median:
                            p1, p2 = median
                            distal = p1 if abs(p1[1] - center[1]) >= abs(p2[1] - center[1]) else p2
                            direction = "up" if distal[1] < center[1] else "down"
                        flag_count = 0
                        for fid in stem_flags.get(stem_id, []):
                            shape = (objs.get(fid).get("shape") if fid in objs else "") or ""
                            m = re.search(r"FLAG_(\d+)", shape.upper())
                            flag_count = max(flag_count, int(m.group(1)) if m else 1)
                        infos.append({
                            "cid": cid,
                            "kind": "head",
                            "staff": _int(cel.get("staff"), 0) or 0,
                            "x_abs": float(center[0]),
                            "y_abs": float(center[1]),
                            "heads": heads,
                            "head_kind": _head_kind([h.get("shape", "") for h in heads]),
                            "stem_id": stem_id,
                            "direction": direction,
                            "distal": distal,
                            "beam_count": len(stem_beams.get(stem_id, set())) if stem_id else 0,
                            "flag_count": flag_count,
                            "assigned_begin_times": list(begin_times.get(cid, [])),
                            "assigned_continue_times": list(continue_times.get(cid, [])),
                        })

                    # Raster beams supplement missing Audiveris beam relations only.
                    if arr is not None:
                        local_groups = defaultdict(list)
                        for info in infos:
                            local_groups[(info["staff"], info["direction"])].append(info)
                        for group in local_groups.values():
                            group.sort(key=lambda r: r["x_abs"])
                            for a, b in zip(group, group[1:]):
                                count = _beam_band_count(arr, a, b, interline)
                                if count:
                                    a["beam_count"] = max(a["beam_count"], count)
                                    b["beam_count"] = max(b["beam_count"], count)

                    events = []
                    for info in infos:
                        base = Fraction(4) if info["head_kind"] == "whole" else Fraction(2) if info["head_kind"] == "half" else Fraction(1)
                        divisions = max(int(info["beam_count"]), int(info["flag_count"]))
                        duration = base / (2 ** divisions) if divisions and base <= 1 else base
                        dot_count = max((dotted_heads.get(str(h.get("id")), 0) for h in info["heads"]), default=0)
                        duration *= _dot_multiplier(dot_count)
                        all_tied = bool(info["heads"]) and all(str(h.get("id")) in tie_right_heads for h in info["heads"])
                        events.append({
                            **info,
                            "duration_quarter": duration,
                            "dot_count": dot_count,
                            "attack": not all_tied,
                            "tie_continuation": all_tied,
                            "rest": False,
                        })

                    for cid in rest_chords:
                        cel = objs.get(cid)
                        cb = _bounds(cel) if cel is not None else None
                        if cel is None or cb is None:
                            continue
                        x, y, w, h = cb
                        members = [objs[m] for m in chord_members.get(cid, []) if m in objs]
                        rests = [m for m in members if _local(m.tag) == "rest"]
                        shape = rests[0].get("shape", "") if rests else ""
                        duration = _rest_duration(shape) or Fraction(1)
                        # A centered whole-rest in an otherwise active staff denotes a
                        # full-measure silence; its printed center is not an onset column.
                        if "WHOLE_REST" in shape.upper() and duration >= full:
                            continue
                        events.append({
                            "cid": cid,
                            "kind": "rest",
                            "staff": _int(cel.get("staff"), 0) or 0,
                            "x_abs": float(x + w / 2),
                            "y_abs": float(y + h / 2),
                            "duration_quarter": duration,
                            "assigned_begin_times": list(begin_times.get(cid, [])),
                            "assigned_continue_times": list(continue_times.get(cid, [])),
                            "attack": False,
                            "tie_continuation": False,
                            "rest": True,
                        })

                    events.sort(key=lambda r: (r["x_abs"], r["staff"], r["cid"]))
                    clusters: list[list[dict]] = []
                    for event in events:
                        if not clusters or event["x_abs"] - clusters[-1][-1]["x_abs"] > cluster_tolerance_px:
                            clusters.append([event])
                        else:
                            clusters[-1].append(event)

                    columns = []
                    for group in clusters:
                        rep = min(group, key=lambda a: (sum(abs(a["x_abs"] - b["x_abs"]) for b in group), a["cid"]))
                        durations = [e["duration_quarter"] for e in group if e.get("duration_quarter", 0) > 0]
                        head_events = [e for e in group if e["kind"] == "head"]
                        columns.append({
                            "x_abs": float(rep["x_abs"]),
                            "y_abs": float(rep["y_abs"]),
                            "events": group,
                            "attack": any(e.get("attack") for e in head_events),
                            "rest": any(e.get("rest") for e in group),
                            "tie_continuation_only": bool(head_events) and all(e.get("tie_continuation") for e in head_events),
                            # A global attack can contain several simultaneous notes.  Keep
                            # the longest sounding duration on the column (the same convention
                            # used by the symbolic Hit model), while the metric lattice below
                            # still considers every constituent duration independently.
                            "duration_quarter": max(durations, default=Fraction(1)),
                            "assigned_begin_times": [t for e in group for t in e.get("assigned_begin_times", [])],
                        })

                    duration_values = [
                        e["duration_quarter"]
                        for c in columns for e in c["events"]
                        if e.get("duration_quarter", 0) > 0
                    ]
                    assigned_unique = sorted({t for c in columns for t in c["assigned_begin_times"] if 0 <= t < full})
                    duration_values.extend(b - a for a, b in zip(assigned_unique, assigned_unique[1:]) if b > a)
                    quantum = _fraction_gcd(duration_values)
                    if quantum > 1:
                        quantum = Fraction(1)
                    while columns and int(full / quantum) < len(columns):
                        quantum /= 2
                    # Do not allow an accidental exotic denominator to explode the grid.
                    if quantum < Fraction(1, 32):
                        quantum = Fraction(1, 32)
                        while columns and int(full / quantum) < len(columns):
                            quantum /= 2

                    selected = _choose_feasible_semantic_anchors(columns, quantum, full) if columns else {}
                    positions, timing_audit = _fill_metric_positions(columns, selected, quantum, full) if columns else ([], {})
                    measure_rows = []
                    for i, (col, grid_index) in enumerate(zip(columns, positions)):
                        onset = Fraction(grid_index) * quantum
                        assigned = list(col["assigned_begin_times"])
                        exact_support = sum(1 for t in assigned if t == onset)
                        if exact_support:
                            source = "semantic-begin-anchor"
                            confidence = min(1.0, 0.90 + 0.02 * exact_support)
                        elif i in selected:
                            source = "semantic-monotonic-anchor"
                            confidence = 0.90
                        else:
                            source = "canonical-grid-interpolation"
                            confidence = 0.72
                        chord_ids = [e["cid"] for e in col["events"] if e["kind"] == "head"]
                        canonical = CanonicalColumn(
                            global_measure_index=global_measure,
                            page_index=page_index,
                            system_index=system_index,
                            stack_index_in_system=stack_index,
                            x_abs=col["x_abs"],
                            y_abs=col["y_abs"],
                            onset_quarter=onset,
                            duration_quarter=col["duration_quarter"],
                            attack=bool(col["attack"]),
                            rest=bool(col["rest"]),
                            tie_continuation_only=bool(col["tie_continuation_only"]),
                            chord_ids=chord_ids,
                            assigned_begin_times=assigned,
                            notation_events=[
                                {
                                    "chord_id": e.get("cid"),
                                    "kind": e.get("kind"),
                                    "staff": int(e.get("staff", 0) or 0),
                                    "duration_quarter": str(e.get("duration_quarter", Fraction(0))),
                                    "dot_count": int(e.get("dot_count", 0) or 0),
                                    "attack": bool(e.get("attack")),
                                    "tie_continuation": bool(e.get("tie_continuation")),
                                    "rest": bool(e.get("rest")),
                                }
                                for e in col["events"]
                            ],
                            timing_source=source,
                            confidence=confidence,
                        )
                        out.append(canonical)
                        measure_rows.append(canonical.row())

                    meta["measures"].append({
                        "global_measure_index": global_measure,
                        "measure_number": measure.number,
                        "page_index": page_index,
                        "system_index": system_index,
                        "stack_index_in_system": stack_index,
                        "stack_left": left,
                        "stack_right": right,
                        "full_duration_quarter": str(full),
                        "quantum_quarter": str(quantum),
                        "physical_column_count": len(columns),
                        "attack_column_count": sum(1 for c in columns if c["attack"]),
                        "timing_audit": timing_audit,
                        "columns": measure_rows,
                    })
                    global_measure += 1
            page_index += 1

    meta["available"] = bool(out)
    meta["column_count"] = len(out)
    meta["attack_column_count"] = sum(1 for c in out if c.attack)
    meta["augmentation_dot_count"] = int(augmentation_relation_count)
    meta["tie_continuation_column_count"] = sum(1 for c in out if c.tie_continuation_only)
    meta["rest_column_count"] = sum(1 for c in out if c.rest)
    return out, meta


def build_hits_from_canonical_score(omr_path, measures, symbolic_hits=None):
    """Return global sonic attacks on the canonical score-time grid.

    Symbolic MusicXML note details are attached only when they agree exactly with the
    recovered measure/time.  They are never allowed to move a visual attack.
    """
    symbolic_hits = list(symbolic_hits or [])
    framework_meta, framework_warnings = _reconcile_measure_framework_with_omr(
        omr_path, measures, symbolic_hits=symbolic_hits
    )
    columns, meta = recover_canonical_columns(omr_path, measures)
    symbolic_by_key = {(int(h.measure_index), h.offset_in_measure): h for h in symbolic_hits}

    grouped = defaultdict(list)
    for col in columns:
        if not col.attack:
            continue
        mi = int(col.global_measure_index)
        if mi < 0 or mi >= len(measures):
            continue
        measure = measures[mi]
        offset = measure.pickup_shift + col.onset_quarter
        if not (Fraction(0) <= offset < measure.full_duration):
            continue
        grouped[(mi, offset)].append(col)

    hits = []
    for (mi, offset), cols in sorted(grouped.items(), key=lambda item: (item[0][0], item[0][1])):
        measure = measures[mi]
        symbolic = symbolic_by_key.get((mi, offset))
        durations = [c.duration_quarter for c in cols if c.duration_quarter > 0]
        hits.append(Hit(
            onset=measure.start + offset,
            duration=max(durations, default=Fraction(0)),
            measure_index=mi,
            measure_number=measure.number,
            offset_in_measure=offset,
            sources=list(symbolic.sources) if symbolic is not None else [],
            canonical_recovered=True,
        ))

    meta = dict(meta)
    meta.update(framework_meta)
    meta["measure_count"] = len(meta.get("measures", []))
    meta["canonical_hit_count"] = len(hits)
    meta["symbolic_hit_count"] = len(symbolic_hits)
    meta["canonical_attack_keys"] = [f"{h.measure_index}:{h.offset_in_measure}" for h in hits]
    warnings = list(framework_warnings)
    if not hits:
        warnings.append("Canonical score-time recovery produced no usable attacks.")
    return hits, warnings, meta
