from __future__ import annotations

"""Canonical score-time recovery for scanned PDF scores.

The tone-metric algorithm must operate in musical time, not in PDF geometry.  This
module reads Audiveris' saved notation graph and builds a measure-local metric grid
first.  Recognized note/rest columns are then assigned to that grid.  PDF x/y is kept
only as provenance for the later drawing stage.

Important rules implemented here:
- augmentation dots extend duration but never create attacks;
- tie continuations occupy a score position but do not create attacks;
- rests occupy score time but do not create attacks;
- triplet attacks are retained on an independent exact ternary timing layer when MusicXML
  or corroborating Audiveris BEGIN semantics provide a defensible score-time position;
- unresolved tuplet notation is never allowed to distort the ordinary binary metric grid;
- an attack in any other voice at the same position still creates a global hit;
- simultaneous/near-coincident noteheads are one physical attack column;
- Audiveris BEGIN slot times are useful constraints, but contradictory ones cannot
  reorder the printed score.  A maximum feasible monotonic subset is used as anchors;
- missing semantic slots are filled on an exact rational metric lattice.  Geometry is
  used only to choose among positions already generated by that lattice.
"""

from collections import Counter, defaultdict
from dataclasses import asdict, dataclass, replace
from fractions import Fraction
from io import BytesIO
from math import gcd
from pathlib import Path, PurePosixPath
from zipfile import ZipFile
import re

import numpy as np
from lxml import etree
from PIL import Image

from .models import Hit, MeasureInfo, NoteAttack


def _local(tag: str) -> str:
    return tag.rsplit("}", 1)[-1].lower()


def _frac(value) -> Fraction | None:
    try:
        return Fraction(str(value))
    except Exception:
        return None


def _int(value, default=None):
    try:
        return int(float(str(value)))
    except Exception:
        return default


def _bounds(el):
    b = next((c for c in el if _local(c.tag) == "bounds"), None)
    if b is None:
        return None
    try:
        return tuple(float(b.get(k)) for k in ("x", "y", "w", "h"))
    except Exception:
        return None


def _median_points(stem_el):
    med = next((c for c in stem_el if _local(c.tag) == "median"), None)
    if med is None:
        return None
    pts = [c for c in med if _local(c.tag) in {"p1", "p2"}]
    if len(pts) < 2:
        return None
    try:
        return (
            (float(pts[0].get("x")), float(pts[0].get("y"))),
            (float(pts[1].get("x")), float(pts[1].get("y"))),
        )
    except Exception:
        return None


def _page_image(zf: ZipFile, sheet_member: str):
    folder = str(PurePosixPath(sheet_member).parent)
    for name in ("BINARY.png", "GRAY.png"):
        member = f"{folder}/{name}"
        if member in zf.namelist():
            im = Image.open(BytesIO(zf.read(member))).convert("L")
            im.load()
            return im
    return None


def _sheet_no(member: str) -> int:
    m = re.search(r"sheet#(\d+)", member, re.I)
    return int(m.group(1)) if m else 10**9


def _corridor_fraction(arr: np.ndarray, p1, p2, offset: float, half: int = 2) -> float:
    x1, y1 = p1
    x2, y2 = p2
    if abs(x2 - x1) < 6:
        return 0.0
    xa = int(min(x1, x2)) + 3
    xb = int(max(x1, x2)) - 3
    if xb <= xa:
        return 0.0
    dark = total = 0
    for x in range(xa, xb + 1):
        t = (x - x1) / (x2 - x1)
        y = y1 + t * (y2 - y1) + offset
        yi = int(round(y))
        y0 = max(0, yi - half)
        y1i = min(arr.shape[0], yi + half + 1)
        col = arr[y0:y1i, x]
        dark += int(np.count_nonzero(col < 128))
        total += int(col.size)
    return dark / total if total else 0.0


def _beam_band_count(arr: np.ndarray, a: dict, b: dict, interline: float) -> int:
    """Supplement missing semantic beam relations from the saved OMR raster.

    Stem direction is used only for local beam recognition, never for voice/timing.
    """
    if not a.get("distal") or not b.get("distal"):
        return 0
    if a.get("direction") != b.get("direction"):
        return 0
    p1, p2 = a["distal"], b["distal"]
    if abs(p2[0] - p1[0]) > max(140.0, interline * 7.0):
        return 0
    inward = 1.0 if a["direction"] == "up" else -1.0
    offsets = [inward * x for x in np.arange(-3.0, max(9.0, interline * 1.55), 2.0)]
    vals = [_corridor_fraction(arr, p1, p2, off, half=2) for off in offsets]
    active = [v >= 0.47 for v in vals]
    clusters = []
    i = 0
    while i < len(active):
        if not active[i]:
            i += 1
            continue
        j = i
        peak = vals[i]
        while j + 1 < len(active) and active[j + 1]:
            j += 1
            peak = max(peak, vals[j])
        if peak >= 0.58 and (j - i + 1) >= 2:
            clusters.append((i, j, peak))
        i = j + 1
    return min(4, len(clusters))


def _head_kind(head_shapes: list[str]) -> str:
    text = " ".join(head_shapes).upper()
    if "WHOLE" in text:
        return "whole"
    if "VOID" in text or "HALF" in text:
        return "half"
    return "black"


def _rest_duration(shape: str) -> Fraction | None:
    s = (shape or "").upper()
    if "LONG_REST" in s:
        return Fraction(8)
    if "WHOLE_REST" in s:
        return Fraction(4)
    if "HALF_REST" in s:
        return Fraction(2)
    if "QUARTER_REST" in s:
        return Fraction(1)
    if "EIGHTH_REST" in s:
        return Fraction(1, 2)
    m = re.search(r"(?:ONE_)?(\d+)(?:TH|ND|ST|RD)_REST", s)
    if m:
        den = int(m.group(1))
        if den > 0:
            return Fraction(4, den)
    return None


def _dot_multiplier(count: int) -> Fraction:
    out = Fraction(1)
    add = Fraction(1, 2)
    for _ in range(max(0, count)):
        out += add
        add /= 2
    return out


def _fraction_gcd(values: list[Fraction]) -> Fraction:
    vals = [v for v in values if v is not None and v > 0]
    if not vals:
        return Fraction(1, 2)
    den = 1
    for v in vals:
        den = den * v.denominator // gcd(den, v.denominator)
    nums = [int(v * den) for v in vals]
    g = nums[0]
    for n in nums[1:]:
        g = gcd(g, n)
    return Fraction(g, den)


@dataclass
class CanonicalColumn:
    global_measure_index: int
    page_index: int
    system_index: int
    stack_index_in_system: int
    x_abs: float
    y_abs: float
    onset_quarter: Fraction
    duration_quarter: Fraction
    attack: bool
    rest: bool
    tie_continuation_only: bool
    chord_ids: list[str]
    assigned_begin_times: list[Fraction]
    notation_events: list[dict]
    timing_source: str
    confidence: float
    tuplet_arity: int | None = None
    tuplet_group: str | None = None

    def row(self) -> dict:
        row = asdict(self)
        row["onset_quarter"] = str(self.onset_quarter)
        row["duration_quarter"] = str(self.duration_quarter)
        row["assigned_begin_times"] = [str(x) for x in self.assigned_begin_times]
        return row


def _choose_feasible_semantic_anchors(columns: list[dict], quantum: Fraction, full: Fraction) -> dict[int, int]:
    """Choose a maximum-support monotonic subset of Audiveris BEGIN times.

    Feasibility includes enough unused metric-grid positions for every intervening
    physical column.  This is the key safeguard against contradictory OMR slot data.
    """
    n = len(columns)
    units = int(full / quantum)
    candidates: list[tuple[int, int, int]] = []
    for i, col in enumerate(columns):
        counts = Counter(col.get("assigned_begin_times", []))
        for t, support in counts.items():
            if t < 0 or t >= full:
                continue
            ratio = t / quantum
            if ratio.denominator != 1:
                continue
            j = int(ratio)
            if j < i or units - 1 - j < n - 1 - i:
                continue
            candidates.append((i, j, int(support)))

    # The leftmost recognized event/rest column defines the measure origin.  If OMR
    # failed to provide it semantically we still place it on the pre-existing t=0 grid.
    anchors: dict[int, int] = {0: 0}
    if n <= 1:
        return anchors

    # Weighted longest feasible path.  Support dominates anchor count.
    candidates = [(i, j, w) for i, j, w in candidates if i > 0 and j > 0]
    dp: list[tuple[int, int, int, int] | None] = [None] * len(candidates)
    parent = [-1] * len(candidates)
    for a, (i, j, w) in enumerate(candidates):
        if j < i:  # must leave one grid position per preceding column
            continue
        best = (w, 1, -j, -i)
        best_parent = -1
        for b in range(a):
            if dp[b] is None:
                continue
            pi, pj, _pw = candidates[b]
            if i <= pi or j - pj < i - pi:
                continue
            score = (dp[b][0] + w, dp[b][1] + 1, -j, -i)
            if score > best:
                best = score
                best_parent = b
        dp[a] = best
        parent[a] = best_parent

    if not dp:
        return anchors
    valid = [i for i, x in enumerate(dp) if x is not None]
    if not valid:
        return anchors
    k = max(valid, key=lambda idx: dp[idx])
    chain = []
    while k >= 0:
        chain.append(candidates[k])
        k = parent[k]
    for i, j, _w in reversed(chain):
        anchors[i] = j
    return anchors


def _fill_metric_positions(columns: list[dict], anchors: dict[int, int], quantum: Fraction, full: Fraction) -> tuple[list[int], dict]:
    n = len(columns)
    units = int(full / quantum)
    if n == 0:
        return [], {}
    anchors = dict(anchors)
    anchors[0] = 0

    # Estimate pixels per grid unit from trusted anchor pairs.
    ordered = sorted(anchors.items())
    scales = []
    for (i0, j0), (i1, j1) in zip(ordered, ordered[1:]):
        if j1 > j0 and columns[i1]["x_abs"] > columns[i0]["x_abs"]:
            scales.append((columns[i1]["x_abs"] - columns[i0]["x_abs"]) / (j1 - j0))
    if scales:
        px_per_unit = sorted(scales)[len(scales) // 2]
    elif n > 1:
        px_per_unit = max(1.0, (columns[-1]["x_abs"] - columns[0]["x_abs"]) / max(1, n - 1))
    else:
        px_per_unit = 1.0

    # If there is no semantic anchor at the right, extrapolate only as far as the
    # notation spacing suggests; never beyond the measure grid.
    last_i, last_j = max(anchors.items())
    if last_i < n - 1:
        dx = columns[-1]["x_abs"] - columns[last_i]["x_abs"]
        estimated = last_j + max(n - 1 - last_i, int(round(dx / max(px_per_unit, 1e-6))))
        last_target = min(units - 1, max(last_j + (n - 1 - last_i), estimated))
        anchors[n - 1] = last_target

    js = [-1] * n
    for i, j in anchors.items():
        js[i] = j

    ordered = sorted(anchors.items())
    for (i0, j0), (i1, j1) in zip(ordered, ordered[1:]):
        count = i1 - i0
        if count <= 1:
            continue
        x0 = columns[i0]["x_abs"]
        x1 = columns[i1]["x_abs"]
        prev = j0
        for i in range(i0 + 1, i1):
            remaining = i1 - i
            if x1 > x0:
                ideal = j0 + (j1 - j0) * ((columns[i]["x_abs"] - x0) / (x1 - x0))
            else:
                ideal = j0 + (j1 - j0) * ((i - i0) / count)
            lo = prev + 1
            hi = j1 - remaining
            j = max(lo, min(hi, int(round(ideal))))
            js[i] = j
            prev = j

    # Defensive fill (should only occur with a one-column measure).
    prev = -1
    for i, j in enumerate(js):
        if j < 0:
            j = min(units - 1, prev + 1)
            js[i] = j
        prev = j

    semantic = _choose_feasible_semantic_anchors(columns, quantum, full)
    audit = {
        "quantum_quarter": str(quantum),
        "grid_units_per_measure": units,
        "semantic_anchor_count": len(semantic),
        "semantic_anchor_indices": {str(i): int(j) for i, j in sorted(semantic.items())},
        "all_timing_anchor_indices": {str(i): int(j) for i, j in sorted(anchors.items())},
        "px_per_grid_unit": float(px_per_unit),
    }
    return js, audit



def _raw_ratio(value: str | None) -> tuple[int, int] | None:
    """Parse an unreduced n/d ratio while preserving the written denominator.

    This matters for meter: 3/4 and 6/8 have the same rational duration but a
    different tactus interpretation in the Tone-Metric engine.
    """
    if value is None:
        return None
    m = re.match(r"^\s*(\d+)\s*/\s*(\d+)\s*$", str(value))
    if not m:
        return None
    n, d = int(m.group(1)), int(m.group(2))
    if n <= 0 or d <= 0:
        return None
    return n, d


def _stack_time_signature(measure_nodes: list, objs: dict[str, object]) -> tuple[int, int] | None:
    """Return an explicit time signature stored in one Audiveris measure stack.

    Audiveris measure nodes refer to time-signature inters through a ``times``
    child.  ``time-rational`` is preferred because it preserves 6/8 vs 3/4.
    Common/cut-time symbols are supported as a defensive fallback.
    """
    found: list[tuple[int, int]] = []
    for meas in measure_nodes:
        times = next((c for c in meas if _local(c.tag) == "times"), None)
        if times is None or not (times.text or "").strip():
            continue
        for oid in times.text.split():
            obj = objs.get(str(oid))
            if obj is None:
                continue
            ratio = _raw_ratio(obj.get("time-rational"))
            if ratio is not None:
                found.append(ratio)
                continue
            shape = (obj.get("shape") or "").upper()
            if "CUT_TIME" in shape or "ALLA_BREVE" in shape:
                found.append((2, 2))
            elif "COMMON_TIME" in shape:
                found.append((4, 4))
    if not found:
        return None
    counts = Counter(found)
    return max(counts, key=lambda x: (counts[x], -found.index(x)))


def _read_omr_measure_stacks(omr_path: str | Path) -> tuple[list[dict], list[str]]:
    """Read the complete physical measure-stack sequence from a saved .omr.

    The returned sequence exists independently of MusicXML export.  This is the
    authoritative measure *cardinality/order* for PDF analyses; MusicXML remains a
    source of symbolic details where Audiveris successfully exported them.
    """
    path = Path(omr_path)
    rows: list[dict] = []
    warnings: list[str] = []
    if not path.exists():
        return rows, ["Saved OMR project not found while building the measure framework."]

    with ZipFile(path, "r") as zf:
        members = sorted(
            [n for n in zf.namelist() if re.search(r"sheet#\d+/sheet#\d+\.xml$", n, re.I)],
            key=_sheet_no,
        )
        page_index = 0
        for member in members:
            try:
                root = etree.fromstring(zf.read(member))
            except Exception as exc:
                warnings.append(f"Could not parse {member} while building the OMR measure framework: {exc}")
                continue
            pages = [e for e in root.iter() if _local(e.tag) == "page"] or [root]
            for page in pages:
                systems = [e for e in page if _local(e.tag) == "system"]
                if not systems:
                    systems = [e for e in page.iter() if _local(e.tag) == "system"]
                for system_index, system in enumerate(systems):
                    objs = {str(e.get("id")): e for e in system.iter() if e.get("id") is not None}
                    stacks = [e for e in system if _local(e.tag) == "stack"]
                    parts = [e for e in system if _local(e.tag) == "part"]
                    part_measures = [[m for m in p if _local(m.tag) == "measure"] for p in parts]
                    for stack_index, stack in enumerate(stacks):
                        measure_nodes = [ms[stack_index] for ms in part_measures if stack_index < len(ms)]
                        expected = _frac(stack.get("expected"))
                        duration = _frac(stack.get("duration"))
                        abnormal = any((m.get("abnormal") or "").lower() in {"true", "1", "yes"} for m in measure_nodes)
                        rows.append({
                            "global_measure_index": len(rows),
                            "page_index": page_index,
                            "system_index": system_index,
                            "stack_index_in_system": stack_index,
                            "stack_id": str(stack.get("id") or ""),
                            "expected_whole": expected,
                            "duration_whole": duration,
                            "explicit_meter": _stack_time_signature(measure_nodes, objs),
                            "abnormal": abnormal,
                        })
                page_index += 1
    return rows, warnings


def _numeric_measure_alignment(measures: list[MeasureInfo], stack_count: int) -> tuple[dict[int, int], int | None]:
    """Conservatively align exported measure numbers to physical OMR stacks.

    Audiveris preserves original printed measure numbers even when PartwiseBuilder
    omits individual measures.  We exploit that only when the numeric span exactly
    equals the physical stack count; otherwise no guess is made.
    """
    parsed: list[int] = []
    for m in measures:
        text = str(m.number).strip()
        if not re.fullmatch(r"-?\d+", text):
            return {}, None
        parsed.append(int(text))
    if not parsed or len(set(parsed)) != len(parsed) or parsed != sorted(parsed):
        return {}, None
    lo, hi = parsed[0], parsed[-1]
    if hi - lo + 1 != stack_count:
        return {}, None
    mapping = {old_i: number - lo for old_i, number in enumerate(parsed)}
    if any(idx < 0 or idx >= stack_count for idx in mapping.values()):
        return {}, None
    return mapping, lo


def reconcile_measure_framework_from_omr(
    omr_path: str | Path,
    measures: list[MeasureInfo],
    symbolic_hits: list[Hit] | None = None,
    initial_meter_override=None,
) -> tuple[list[MeasureInfo], list[Hit], list[str], dict]:
    """Rebuild the PDF measure/time framework from the complete saved OMR project.

    This fixes an Audiveris export failure mode in which the .omr contains all
    physical measure stacks but PartwiseBuilder silently omits some measures from
    MusicXML.  The function never invents omitted *attacks*: it restores the full
    measure sequence, after which :func:`recover_canonical_columns` reads attacks
    directly from those OMR stacks.

    Existing exported measures keep their validated meter/pickup metadata. Missing
    measures inherit the active meter (or an explicit OMR time signature) and are
    assigned ordinary full-measure timing.  The mapping is applied only when it is
    unambiguous; otherwise the original MusicXML framework is returned unchanged.
    """
    stacks, warnings = _read_omr_measure_stacks(omr_path)
    symbolic_hits = list(symbolic_hits or [])
    meta = {
        "source": "musicxml",
        "omr_stack_count": len(stacks),
        "musicxml_measure_count": len(measures),
        "expanded_measure_count": len(measures),
        "synthesized_missing_measure_count": 0,
        "synthesized_missing_measure_numbers": [],
        "alignment": "unchanged",
    }
    if not stacks or not measures:
        return list(measures), symbolic_hits, warnings, meta
    if len(stacks) == len(measures):
        meta.update({"source": "omr-cardinality+musicxml-metadata", "alignment": "direct-index"})
        return list(measures), symbolic_hits, warnings, meta
    if len(stacks) < len(measures):
        warnings.append(
            f"OMR has {len(stacks)} physical measure stacks but MusicXML has {len(measures)} measures; "
            "the MusicXML framework was retained because expansion would be unsafe."
        )
        return list(measures), symbolic_hits, warnings, meta

    old_to_new, numeric_start = _numeric_measure_alignment(measures, len(stacks))
    if not old_to_new:
        warnings.append(
            f"OMR has {len(stacks)} physical measure stacks but MusicXML has {len(measures)} measures. "
            "Their numbering could not be aligned unambiguously, so the MusicXML framework was retained."
        )
        return list(measures), symbolic_hits, warnings, meta

    known_by_new = {new_i: measures[old_i] for old_i, new_i in old_to_new.items()}
    old_index_by_new = {new_i: old_i for old_i, new_i in old_to_new.items()}
    meter_override = None
    if initial_meter_override:
        try:
            meter_override = tuple(int(x) for x in initial_meter_override)
            if len(meter_override) != 2 or min(meter_override) <= 0:
                meter_override = None
        except Exception:
            meter_override = None

    current_meter: tuple[int, int] | None = meter_override
    if current_meter is None and 0 in known_by_new:
        km = known_by_new[0]
        current_meter = (int(km.numerator), int(km.denominator))
    if current_meter is None and stacks[0].get("explicit_meter"):
        current_meter = tuple(stacks[0]["explicit_meter"])
    if current_meter is None:
        raw = stacks[0].get("expected_whole")
        if raw and raw > 0:
            current_meter = (int(raw.numerator), int(raw.denominator))
            warnings.append(
                f"Initial meter was inferred from OMR expected measure duration as {current_meter[0]}/{current_meter[1]}; "
                "compound/simple notation could not be distinguished from duration alone."
            )
    if current_meter is None:
        current_meter = (4, 4)
        warnings.append("No initial meter could be recovered from MusicXML or OMR; 4/4 was used as a safe fallback.")

    expanded: list[MeasureInfo] = []
    synthesized_numbers: list[str] = []
    cumulative = Fraction(0)
    for i, stack in enumerate(stacks):
        known = known_by_new.get(i)
        explicit = stack.get("explicit_meter")
        if i == 0 and meter_override is not None:
            current_meter = meter_override
        elif known is not None:
            known_meter = (int(known.numerator), int(known.denominator))
            if explicit is not None and tuple(explicit) != known_meter:
                warnings.append(
                    f"Measure {known.number}: OMR time signature {explicit[0]}/{explicit[1]} disagrees with "
                    f"MusicXML {known_meter[0]}/{known_meter[1]}; MusicXML was retained for this exported measure."
                )
            current_meter = known_meter
        elif explicit is not None:
            current_meter = tuple(explicit)

        num, den = current_meter
        full = Fraction(num * 4, den)
        expected = stack.get("expected_whole")
        expected_q = expected * 4 if expected is not None else None
        if expected_q is not None and expected_q > 0 and expected_q != full:
            warnings.append(
                f"Physical measure {i + 1}: OMR expected duration {expected_q} quarter-notes disagrees with "
                f"active meter {num}/{den} ({full}); the explicit/validated meter was retained."
            )

        if known is not None:
            number = str(known.number)
            actual = known.actual_duration
            shift = known.pickup_shift
            implicit = bool(known.implicit)
        else:
            number = str((numeric_start if numeric_start is not None else 1) + i)
            synthesized_numbers.append(number)
            actual = full
            shift = Fraction(0)
            implicit = False
            # Only the opening physical measure can be a pickup without creating a
            # discontinuity in later score time.  Use OMR abnormal+short duration as
            # evidence; do not interpret under/overfull interior OMR durations as meter.
            if i == 0 and stack.get("abnormal") and stack.get("duration_whole"):
                aq = stack["duration_whole"] * 4
                if Fraction(0) < aq < full:
                    actual = aq
                    shift = full - aq
                    implicit = True

        expanded.append(MeasureInfo(
            index=i,
            number=number,
            start=cumulative,
            full_duration=full,
            actual_duration=actual,
            pickup_shift=shift,
            numerator=num,
            denominator=den,
            implicit=implicit,
        ))
        cumulative += full

    remapped_hits: list[Hit] = []
    for h in symbolic_hits:
        new_i = old_to_new.get(int(h.measure_index))
        if new_i is None or new_i >= len(expanded):
            continue
        m = expanded[new_i]
        old_measure_start = h.onset - h.offset_in_measure
        timeline_delta = m.start - old_measure_start
        new_sources: list[NoteAttack] = []
        for src in h.sources:
            src_offset = src.offset_in_measure
            new_sources.append(replace(
                src,
                onset=m.start + src_offset,
                measure_index=new_i,
                measure_number=m.number,
                tuplet_span_start=(src.tuplet_span_start + timeline_delta if src.tuplet_span_start is not None else None),
                tuplet_span_end=(src.tuplet_span_end + timeline_delta if src.tuplet_span_end is not None else None),
            ))
        remapped_hits.append(replace(
            h,
            onset=m.start + h.offset_in_measure,
            measure_index=new_i,
            measure_number=m.number,
            sources=new_sources,
            tuplet_span_start=(h.tuplet_span_start + timeline_delta if h.tuplet_span_start is not None else None),
            tuplet_span_end=(h.tuplet_span_end + timeline_delta if h.tuplet_span_end is not None else None),
        ))

    meta.update({
        "source": "omr-complete-measure-framework",
        "alignment": "numeric-measure-number-span",
        "numeric_measure_start": numeric_start,
        "expanded_measure_count": len(expanded),
        "synthesized_missing_measure_count": len(synthesized_numbers),
        "synthesized_missing_measure_numbers": synthesized_numbers,
        "remapped_symbolic_hit_count": len(remapped_hits),
    })
    if synthesized_numbers:
        warnings.append(
            f"Restored {len(synthesized_numbers)} measure(s) omitted from Audiveris MusicXML export "
            f"using the complete OMR stack sequence: {', '.join(synthesized_numbers[:20])}"
            + (" ..." if len(synthesized_numbers) > 20 else "")
        )
    return expanded, remapped_hits, warnings, meta

def _single_valid_begin_time(group: list[dict], full: Fraction) -> Fraction | None:
    """Return one corroborating OMR BEGIN value when a group has exactly one.

    Audiveris slot offsets are not trusted as absolute score time here.  Their
    equality is used only as independent evidence that two nearby cross-staff
    attack groups denote the same simultaneous event.
    """
    values = {
        t for event in group for t in event.get("assigned_begin_times", [])
        if Fraction(0) <= t < full
    }
    return next(iter(values)) if len(values) == 1 else None


def _merge_cross_staff_simultaneous_clusters(
    clusters: list[list[dict]],
    full: Fraction,
    interline: float,
    cluster_tolerance_px: float,
) -> list[list[dict]]:
    """Merge only strongly corroborated cross-staff simultaneities.

    The ordinary x-cluster tolerance remains deliberately tight so rapid
    successive attacks on one staff stay distinct.  A second adjacent group is
    merged only when (1) the attack staves are disjoint, (2) both groups carry
    the same single valid Audiveris BEGIN value, and (3) their horizontal gap is
    no larger than about one staff interline.  This corrects chord-box offsets
    caused by accidentals/stems without using Audiveris slot time as the active
    score-time grid.
    """
    if not clusters:
        return []
    tolerance = max(float(cluster_tolerance_px), float(interline) * 1.10)
    merged: list[list[dict]] = []
    for group in clusters:
        if merged:
            previous = merged[-1]
            prev_heads = [e for e in previous if e.get("kind") == "head" and e.get("attack")]
            curr_heads = [e for e in group if e.get("kind") == "head" and e.get("attack")]
            prev_staves = {int(e.get("staff", 0) or 0) for e in prev_heads}
            curr_staves = {int(e.get("staff", 0) or 0) for e in curr_heads}
            prev_time = _single_valid_begin_time(previous, full)
            curr_time = _single_valid_begin_time(group, full)
            gap = float(group[0]["x_abs"] - previous[-1]["x_abs"])
            if (
                prev_heads and curr_heads
                and prev_staves.isdisjoint(curr_staves)
                and prev_time is not None and prev_time == curr_time
                and gap <= tolerance
            ):
                previous.extend(group)
                previous.sort(key=lambda row: (row["x_abs"], row["staff"], row["cid"]))
                continue
        merged.append(list(group))
    return merged


def recover_canonical_columns(omr_path: str | Path, measures, cluster_tolerance_px: float = 12.0, symbolic_hits=None) -> tuple[list[CanonicalColumn], dict]:
    path = Path(omr_path)
    out: list[CanonicalColumn] = []
    meta = {
        "available": False,
        "warnings": [],
        "measures": [],
        "page_dimensions": {},
        "architecture": "metric-grid-first/notation-semantics/global-attack-map",
    }
    symbolic_hits = list(symbolic_hits or [])
    symbolic_tuplet_offsets = defaultdict(list)
    for h in symbolic_hits:
        if any(getattr(src, "tuplet_actual_notes", None) for src in getattr(h, "sources", [])):
            mi = int(h.measure_index)
            if 0 <= mi < len(measures):
                local = h.offset_in_measure - measures[mi].pickup_shift
                if Fraction(0) <= local < measures[mi].full_duration:
                    symbolic_tuplet_offsets[mi].append(local)
    for mi in list(symbolic_tuplet_offsets):
        symbolic_tuplet_offsets[mi] = sorted(set(symbolic_tuplet_offsets[mi]))
    if not path.exists():
        meta["warnings"].append("Saved OMR project not found.")
        return out, meta

    global_measure = 0
    page_index = 0
    augmentation_relation_count = 0
    recognized_tuplet_chord_count = 0
    recovered_tuplet_chord_count = 0
    recovered_tuplet_column_count = 0
    unresolved_tuplet_chord_count = 0
    unresolved_tuplet_column_count = 0
    cross_staff_simultaneity_merge_count = 0
    with ZipFile(path, "r") as zf:
        members = sorted(
            [n for n in zf.namelist() if re.search(r"sheet#\d+/sheet#\d+\.xml$", n, re.I)],
            key=_sheet_no,
        )
        for member in members:
            root = etree.fromstring(zf.read(member))
            image = _page_image(zf, member)
            arr = np.asarray(image) if image is not None else None
            if image is not None:
                meta["page_dimensions"][str(page_index)] = [int(image.width), int(image.height)]
            interline = 19.0
            il = next((e for e in root.iter() if _local(e.tag) == "interline"), None)
            if il is not None:
                interline = float(il.get("main") or il.get("min") or interline)

            systems = [e for e in root.iter() if _local(e.tag) == "system"]
            for system_index, system in enumerate(systems):
                objs = {str(e.get("id")): e for e in system.iter() if e.get("id") is not None}
                rels = []
                for rel in system.iter():
                    if _local(rel.tag) != "relation":
                        continue
                    typ = next((_local(c.tag) for c in rel if isinstance(c.tag, str)), "")
                    rels.append((str(rel.get("source") or ""), str(rel.get("target") or ""), typ, rel))

                chord_members = defaultdict(list)
                chord_stem = {}
                stem_beams = defaultdict(set)
                stem_flags = defaultdict(list)
                dotted_heads = Counter()
                tie_right_heads = set()
                tuplet_chords = set()
                chord_tuplet_id = {}
                tuplet_shapes = {}
                for source, target, typ, rel in rels:
                    if typ == "containment" and source in objs and target in objs:
                        if _local(objs[source].tag) in {"head-chord", "rest-chord"}:
                            chord_members[source].append(target)
                    elif typ == "chord-stem":
                        chord_stem[source] = target
                    elif typ == "beam-stem":
                        stem_beams[target].add(source)
                    elif typ == "flag-stem":
                        stem_flags[target].append(source)
                    elif typ == "chord-tuplet":
                        chord_id = None
                        tuplet_id = None
                        if source in objs and _local(objs[source].tag) in {"head-chord", "rest-chord"}:
                            chord_id, tuplet_id = source, target
                        elif target in objs and _local(objs[target].tag) in {"head-chord", "rest-chord"}:
                            chord_id, tuplet_id = target, source
                        if chord_id is not None:
                            tuplet_chords.add(chord_id)
                            chord_tuplet_id[chord_id] = tuplet_id
                            tel = objs.get(tuplet_id)
                            if tel is not None:
                                tuplet_shapes[tuplet_id] = (tel.get("shape") or "").upper()
                    elif typ == "augmentation" and source in objs and target in objs:
                        augmentation_relation_count += 1
                        if _local(objs[source].tag) == "head":
                            dotted_heads[source] += 1
                        elif _local(objs[target].tag) == "head":
                            dotted_heads[target] += 1
                    elif typ == "slur-head" and source in objs and target in objs:
                        slur = objs[source]
                        if _local(slur.tag) == "slur" and (slur.get("tie") or "").lower() == "true":
                            spec = next((c for c in rel if _local(c.tag) == "slur-head"), None)
                            if spec is not None and (spec.get("side") or "").upper() == "RIGHT":
                                tie_right_heads.add(target)

                stacks = [e for e in system if _local(e.tag) == "stack"]
                parts = [e for e in system if _local(e.tag) == "part"]
                part_measures = [[m for m in p if _local(m.tag) == "measure"] for p in parts]

                for stack_index, stack in enumerate(stacks):
                    if global_measure >= len(measures):
                        meta["warnings"].append("OMR contains more measure stacks than the canonical MusicXML framework.")
                        break
                    measure = measures[global_measure]
                    full = measure.full_duration
                    left = float(stack.get("left") or 0.0)
                    right = float(stack.get("right") or left + 1.0)
                    slot_time = {}
                    for sl in stack:
                        if _local(sl.tag) == "slot":
                            key = str(sl.get("id") or "")
                            t = _frac(sl.get("time-offset"))
                            if key and t is not None:
                                slot_time[key] = t * 4

                    measure_nodes = [ms[stack_index] for ms in part_measures if stack_index < len(ms)]
                    head_chords: list[str] = []
                    rest_chords: list[str] = []
                    begin_times = defaultdict(list)
                    continue_times = defaultdict(list)
                    for meas in measure_nodes:
                        for tag, bucket in (("head-chords", head_chords), ("rest-chords", rest_chords)):
                            el = next((c for c in meas if _local(c.tag) == tag), None)
                            if el is not None and el.text:
                                bucket.extend(el.text.split())
                        for voice in [c for c in meas if _local(c.tag) == "voice"]:
                            slots_el = next((c for c in voice if _local(c.tag) == "slots"), None)
                            if slots_el is None:
                                continue
                            for entry in [c for c in slots_el if _local(c.tag) == "entry"]:
                                key = next((c for c in entry if _local(c.tag) == "key"), None)
                                val = next((c for c in entry if _local(c.tag) == "value"), None)
                                if key is None or val is None or not key.text:
                                    continue
                                cid = val.get("chord")
                                t = slot_time.get(key.text.strip())
                                if not cid or t is None:
                                    continue
                                if (val.get("status") or "").upper() == "BEGIN":
                                    begin_times[str(cid)].append(t)
                                else:
                                    continue_times[str(cid)].append(t)

                    head_chords = list(dict.fromkeys(head_chords))
                    rest_chords = list(dict.fromkeys(rest_chords))
                    infos = []
                    # First pass: geometry, semantic beams/flags, tie/dot identity.
                    for cid in head_chords:
                        cel = objs.get(cid)
                        cb = _bounds(cel) if cel is not None else None
                        if cel is None or cb is None:
                            continue
                        x, y, w, h = cb
                        members = [objs[m] for m in chord_members.get(cid, []) if m in objs]
                        heads = [m for m in members if _local(m.tag) == "head"]
                        hb = [_bounds(hd) for hd in heads]
                        hb = [b for b in hb if b]
                        hcx = [a + c / 2 for a, b, c, d in hb]
                        hcy = [b + d / 2 for a, b, c, d in hb]
                        # Horizontal registration uses the physical chord box center.  We do
                        # not average multiple independent attack columns; notehead y-centers
                        # are used only to keep the vertical guide near the sounding heads.
                        center = (x + w / 2, sum(hcy) / len(hcy)) if hcy else (x + w / 2, y + h / 2)
                        stem_id = chord_stem.get(cid)
                        stem = objs.get(stem_id) if stem_id else None
                        median = _median_points(stem) if stem is not None else None
                        direction = "none"
                        distal = None
                        if median:
                            p1, p2 = median
                            distal = p1 if abs(p1[1] - center[1]) >= abs(p2[1] - center[1]) else p2
                            direction = "up" if distal[1] < center[1] else "down"
                        flag_count = 0
                        for fid in stem_flags.get(stem_id, []):
                            shape = (objs.get(fid).get("shape") if fid in objs else "") or ""
                            m = re.search(r"FLAG_(\d+)", shape.upper())
                            flag_count = max(flag_count, int(m.group(1)) if m else 1)
                        infos.append({
                            "cid": cid,
                            "kind": "head",
                            "staff": _int(cel.get("staff"), 0) or 0,
                            "x_abs": float(center[0]),
                            "y_abs": float(center[1]),
                            "heads": heads,
                            "head_kind": _head_kind([h.get("shape", "") for h in heads]),
                            "stem_id": stem_id,
                            "direction": direction,
                            "distal": distal,
                            "beam_count": len(stem_beams.get(stem_id, set())) if stem_id else 0,
                            "flag_count": flag_count,
                            "assigned_begin_times": list(begin_times.get(cid, [])),
                            "assigned_continue_times": list(continue_times.get(cid, [])),
                            "tuplet": cid in tuplet_chords,
                            "tuplet_id": chord_tuplet_id.get(cid),
                            "tuplet_shape": tuplet_shapes.get(chord_tuplet_id.get(cid), ""),
                        })

                    # Raster beams supplement missing Audiveris beam relations only.
                    if arr is not None:
                        local_groups = defaultdict(list)
                        for info in infos:
                            local_groups[(info["staff"], info["direction"])].append(info)
                        for group in local_groups.values():
                            group.sort(key=lambda r: r["x_abs"])
                            for a, b in zip(group, group[1:]):
                                count = _beam_band_count(arr, a, b, interline)
                                if count:
                                    a["beam_count"] = max(a["beam_count"], count)
                                    b["beam_count"] = max(b["beam_count"], count)

                    events = []
                    for info in infos:
                        base = Fraction(4) if info["head_kind"] == "whole" else Fraction(2) if info["head_kind"] == "half" else Fraction(1)
                        divisions = max(int(info["beam_count"]), int(info["flag_count"]))
                        duration = base / (2 ** divisions) if divisions and base <= 1 else base
                        dot_count = max((dotted_heads.get(str(h.get("id")), 0) for h in info["heads"]), default=0)
                        duration *= _dot_multiplier(dot_count)
                        all_tied = bool(info["heads"]) and all(str(h.get("id")) in tie_right_heads for h in info["heads"])
                        events.append({
                            **info,
                            "duration_quarter": duration,
                            "dot_count": dot_count,
                            "attack": (not all_tied),
                            "tie_continuation": all_tied,
                            "rest": False,
                        })

                    for cid in rest_chords:
                        cel = objs.get(cid)
                        cb = _bounds(cel) if cel is not None else None
                        if cel is None or cb is None:
                            continue
                        x, y, w, h = cb
                        members = [objs[m] for m in chord_members.get(cid, []) if m in objs]
                        rests = [m for m in members if _local(m.tag) == "rest"]
                        shape = rests[0].get("shape", "") if rests else ""
                        duration = _rest_duration(shape) or Fraction(1)
                        # A centered whole-rest in an otherwise active staff denotes a
                        # full-measure silence; its printed center is not an onset column.
                        if "WHOLE_REST" in shape.upper() and duration >= full:
                            continue
                        events.append({
                            "cid": cid,
                            "kind": "rest",
                            "staff": _int(cel.get("staff"), 0) or 0,
                            "x_abs": float(x + w / 2),
                            "y_abs": float(y + h / 2),
                            "duration_quarter": duration,
                            "assigned_begin_times": list(begin_times.get(cid, [])),
                            "assigned_continue_times": list(continue_times.get(cid, [])),
                            "attack": False,
                            "tie_continuation": False,
                            "rest": True,
                        })

                    tuplet_events = [e for e in events if e.get("kind") == "head" and e.get("tuplet")]
                    recognized_tuplet_chord_count += len(tuplet_events)
                    # Tuplets are timed independently from the ordinary metric lattice.
                    # This prevents 1/3, 1/6, ... positions from perturbing binary
                    # attacks in other voices while still retaining defensible triplet attacks.
                    events = [e for e in events if not (e.get("kind") == "head" and e.get("tuplet"))]
                    events.sort(key=lambda r: (r["x_abs"], r["staff"], r["cid"]))
                    clusters: list[list[dict]] = []
                    for event in events:
                        if not clusters or event["x_abs"] - clusters[-1][-1]["x_abs"] > cluster_tolerance_px:
                            clusters.append([event])
                        else:
                            clusters[-1].append(event)
                    pre_merge_cluster_count = len(clusters)
                    clusters = _merge_cross_staff_simultaneous_clusters(
                        clusters, full, interline, cluster_tolerance_px
                    )
                    cross_staff_simultaneity_merge_count += pre_merge_cluster_count - len(clusters)

                    columns = []
                    for group in clusters:
                        rep = min(group, key=lambda a: (sum(abs(a["x_abs"] - b["x_abs"]) for b in group), a["cid"]))
                        durations = [e["duration_quarter"] for e in group if e.get("duration_quarter", 0) > 0]
                        head_events = [e for e in group if e["kind"] == "head"]
                        columns.append({
                            "x_abs": float(rep["x_abs"]),
                            "y_abs": float(rep["y_abs"]),
                            "events": group,
                            "attack": any(e.get("attack") for e in head_events),
                            "rest": any(e.get("rest") for e in group),
                            "tie_continuation_only": bool(head_events) and all(e.get("tie_continuation") for e in head_events),
                            # A global attack can contain several simultaneous notes.  Keep
                            # the longest sounding duration on the column (the same convention
                            # used by the symbolic Hit model), while the metric lattice below
                            # still considers every constituent duration independently.
                            "duration_quarter": max(durations, default=Fraction(1)),
                            "assigned_begin_times": [t for e in group for t in e.get("assigned_begin_times", [])],
                        })

                    duration_values = [
                        e["duration_quarter"]
                        for c in columns for e in c["events"]
                        if e.get("duration_quarter", 0) > 0
                    ]
                    # The ordinary metric lattice is derived from non-tuplet durations only.
                    # Audiveris BEGIN times are retained as optional anchors below, but their
                    # differences must not define the lattice: conflicting voice slots and
                    # the independent tuplet layer can otherwise introduce 1/3, 1/6, ... units
                    # into an otherwise binary/dotted notated surface.  A semantic BEGIN time
                    # is accepted only when it lies exactly on this duration-derived grid.
                    quantum = _fraction_gcd(duration_values)
                    if quantum > 1:
                        quantum = Fraction(1)
                    while columns and int(full / quantum) < len(columns):
                        quantum /= 2
                    # Do not allow an accidental exotic denominator to explode the grid.
                    if quantum < Fraction(1, 32):
                        quantum = Fraction(1, 32)
                        while columns and int(full / quantum) < len(columns):
                            quantum /= 2

                    selected = _choose_feasible_semantic_anchors(columns, quantum, full) if columns else {}
                    positions, timing_audit = _fill_metric_positions(columns, selected, quantum, full) if columns else ([], {})
                    measure_rows = []
                    for i, (col, grid_index) in enumerate(zip(columns, positions)):
                        onset = Fraction(grid_index) * quantum
                        assigned = list(col["assigned_begin_times"])
                        exact_support = sum(1 for t in assigned if t == onset)
                        if exact_support:
                            source = "semantic-begin-anchor"
                            confidence = min(1.0, 0.90 + 0.02 * exact_support)
                        elif i in selected:
                            source = "semantic-monotonic-anchor"
                            confidence = 0.90
                        else:
                            source = "canonical-grid-interpolation"
                            confidence = 0.72
                        chord_ids = [e["cid"] for e in col["events"] if e["kind"] == "head"]
                        canonical = CanonicalColumn(
                            global_measure_index=global_measure,
                            page_index=page_index,
                            system_index=system_index,
                            stack_index_in_system=stack_index,
                            x_abs=col["x_abs"],
                            y_abs=col["y_abs"],
                            onset_quarter=onset,
                            duration_quarter=col["duration_quarter"],
                            attack=bool(col["attack"]),
                            rest=bool(col["rest"]),
                            tie_continuation_only=bool(col["tie_continuation_only"]),
                            chord_ids=chord_ids,
                            assigned_begin_times=assigned,
                            notation_events=[
                                {
                                    "chord_id": e.get("cid"),
                                    "kind": e.get("kind"),
                                    "staff": int(e.get("staff", 0) or 0),
                                    "duration_quarter": str(e.get("duration_quarter", Fraction(0))),
                                    "dot_count": int(e.get("dot_count", 0) or 0),
                                    "attack": bool(e.get("attack")),
                                    "tie_continuation": bool(e.get("tie_continuation")),
                                    "rest": bool(e.get("rest")),
                                    "tuplet": bool(e.get("tuplet")),
                                }
                                for e in col["events"]
                            ],
                            timing_source=source,
                            confidence=confidence,
                        )
                        out.append(canonical)
                        measure_rows.append(canonical.row())

                    # Recover triplet columns without changing the ordinary binary grid.
                    # Prefer exact MusicXML time-modification offsets when the exported
                    # symbolic count matches the visible OMR triplet columns.  Otherwise
                    # accept a single valid Audiveris BEGIN value for that physical column.
                    tuplet_clusters = []
                    for event in sorted(tuplet_events, key=lambda r: (r["x_abs"], r["staff"], r["cid"])):
                        if not tuplet_clusters or event["x_abs"] - tuplet_clusters[-1][-1]["x_abs"] > cluster_tolerance_px:
                            tuplet_clusters.append([event])
                        else:
                            tuplet_clusters[-1].append(event)
                    if tuplet_clusters:
                        tuplet_clusters = _merge_cross_staff_simultaneous_clusters(
                            tuplet_clusters, full, interline, cluster_tolerance_px
                        )
                    symbolic_offsets = list(symbolic_tuplet_offsets.get(global_measure, []))
                    use_symbolic_order = bool(tuplet_clusters) and len(symbolic_offsets) == len(tuplet_clusters)
                    unresolved_here = 0
                    for ti, group in enumerate(tuplet_clusters):
                        onset = symbolic_offsets[ti] if use_symbolic_order else _single_valid_begin_time(group, full)
                        if onset is None or not (Fraction(0) <= onset < full):
                            unresolved_here += 1
                            unresolved_tuplet_chord_count += len(group)
                            continue
                        rep = min(group, key=lambda a: (sum(abs(a["x_abs"] - b["x_abs"]) for b in group), a["cid"]))
                        raw_durations = [e["duration_quarter"] for e in group if e.get("duration_quarter", 0) > 0]
                        # Audiveris notehead/beam duration is the written value.  For a
                        # standard TUPLET_THREE relation, three written values occupy the
                        # time of two, so the sounding duration is scaled by 2/3.
                        durations = [d * Fraction(2, 3) if "THREE" in (e.get("tuplet_shape") or "") else d for e, d in [(e, e["duration_quarter"]) for e in group if e.get("duration_quarter", 0) > 0]]
                        canonical = CanonicalColumn(
                            global_measure_index=global_measure,
                            page_index=page_index,
                            system_index=system_index,
                            stack_index_in_system=stack_index,
                            x_abs=float(rep["x_abs"]),
                            y_abs=float(rep["y_abs"]),
                            onset_quarter=onset,
                            duration_quarter=max(durations, default=max(raw_durations, default=Fraction(0))),
                            attack=any(e.get("attack") for e in group),
                            rest=False,
                            tie_continuation_only=bool(group) and all(e.get("tie_continuation") for e in group),
                            chord_ids=[e["cid"] for e in group],
                            assigned_begin_times=[t for e in group for t in e.get("assigned_begin_times", [])],
                            notation_events=[
                                {
                                    "chord_id": e.get("cid"),
                                    "kind": e.get("kind"),
                                    "staff": int(e.get("staff", 0) or 0),
                                    "duration_quarter": str(e.get("duration_quarter", Fraction(0))),
                                    "dot_count": int(e.get("dot_count", 0) or 0),
                                    "attack": bool(e.get("attack")),
                                    "tie_continuation": bool(e.get("tie_continuation")),
                                    "rest": False,
                                    "tuplet": True,
                                    "tuplet_id": e.get("tuplet_id"),
                                    "tuplet_shape": e.get("tuplet_shape"),
                                }
                                for e in group
                            ],
                            timing_source="symbolic-tuplet-time" if use_symbolic_order else "semantic-tuplet-begin",
                            confidence=0.98 if use_symbolic_order else 0.90,
                            tuplet_arity=3 if any("THREE" in (e.get("tuplet_shape") or "") for e in group) else None,
                            tuplet_group=(f"p{page_index}:s{system_index}:{next((e.get('tuplet_id') for e in group if e.get('tuplet_id')), 'tuplet')}"),
                        )
                        out.append(canonical)
                        measure_rows.append(canonical.row())
                        recovered_tuplet_column_count += 1
                        recovered_tuplet_chord_count += len(group)
                    unresolved_tuplet_column_count += unresolved_here
                    measure_rows.sort(key=lambda row: (Fraction(row["onset_quarter"]), float(row["x_abs"])))

                    meta["measures"].append({
                        "global_measure_index": global_measure,
                        "measure_number": measure.number,
                        "page_index": page_index,
                        "system_index": system_index,
                        "stack_index_in_system": stack_index,
                        "stack_left": left,
                        "stack_right": right,
                        "full_duration_quarter": str(full),
                        "quantum_quarter": str(quantum),
                        "physical_column_count": len(columns),
                        "attack_column_count": sum(1 for c in columns if c["attack"]),
                        "timing_audit": timing_audit,
                        "columns": measure_rows,
                    })
                    global_measure += 1
            page_index += 1

    meta["available"] = bool(out)
    meta["column_count"] = len(out)
    meta["attack_column_count"] = sum(1 for c in out if c.attack)
    meta["augmentation_dot_count"] = int(augmentation_relation_count)
    meta["recognized_tuplet_chord_count"] = int(recognized_tuplet_chord_count)
    meta["recovered_tuplet_chord_count"] = int(recovered_tuplet_chord_count)
    meta["recovered_tuplet_column_count"] = int(recovered_tuplet_column_count)
    meta["unresolved_tuplet_chord_count"] = int(unresolved_tuplet_chord_count)
    meta["unresolved_tuplet_column_count"] = int(unresolved_tuplet_column_count)
    # Backward-compatible debug keys: these now mean unresolved/omitted tuplets.
    meta["ignored_tuplet_chord_count"] = int(unresolved_tuplet_chord_count)
    meta["ignored_tuplet_column_count"] = int(unresolved_tuplet_column_count)
    if unresolved_tuplet_column_count:
        meta["warnings"].append(
            f"{unresolved_tuplet_column_count} OMR tuplet column(s) lacked a defensible exact score-time position and were not guessed; symbolic MusicXML tuplets remain eligible when available."
        )
    meta["cross_staff_simultaneity_merge_count"] = int(cross_staff_simultaneity_merge_count)
    meta["tie_continuation_column_count"] = sum(1 for c in out if c.tie_continuation_only)
    meta["rest_column_count"] = sum(1 for c in out if c.rest)
    return out, meta


def build_hits_from_canonical_score(omr_path, measures, symbolic_hits=None):
    """Return global sonic attacks on the canonical score-time grid.

    Symbolic MusicXML note details are attached only when they agree exactly with the
    recovered measure/time.  They are never allowed to move a visual attack.
    """
    columns, meta = recover_canonical_columns(omr_path, measures, symbolic_hits=symbolic_hits)
    symbolic_hits = list(symbolic_hits or [])
    symbolic_by_key = {(int(h.measure_index), h.offset_in_measure): h for h in symbolic_hits}

    grouped = defaultdict(list)
    for col in columns:
        if not col.attack:
            continue
        mi = int(col.global_measure_index)
        if mi < 0 or mi >= len(measures):
            continue
        measure = measures[mi]
        offset = measure.pickup_shift + col.onset_quarter
        if not (Fraction(0) <= offset < measure.full_duration):
            continue
        grouped[(mi, offset)].append(col)

    hits = []
    for (mi, offset), cols in sorted(grouped.items(), key=lambda item: (item[0][0], item[0][1])):
        measure = measures[mi]
        symbolic = symbolic_by_key.get((mi, offset))
        durations = [c.duration_quarter for c in cols if c.duration_quarter > 0]
        tuple_cols = [c for c in cols if getattr(c, "tuplet_arity", None)]
        tuple_groups = {c.tuplet_group for c in tuple_cols if c.tuplet_group}
        symbolic_tuple_arity = getattr(symbolic, "tuplet_arity", None) if symbolic is not None else None
        symbolic_tuple_group = getattr(symbolic, "tuplet_group", None) if symbolic is not None else None
        hits.append(Hit(
            onset=measure.start + offset,
            duration=max(durations, default=Fraction(0)),
            measure_index=mi,
            measure_number=measure.number,
            offset_in_measure=offset,
            sources=list(symbolic.sources) if symbolic is not None else [],
            tuplet_arity=(symbolic_tuple_arity or (3 if any(c.tuplet_arity == 3 for c in tuple_cols) else None)),
            tuplet_group=(symbolic_tuple_group or (next(iter(tuple_groups)) if len(tuple_groups) == 1 else None)),
            tuplet_span_start=(getattr(symbolic, "tuplet_span_start", None) if symbolic is not None else None),
            tuplet_span_end=(getattr(symbolic, "tuplet_span_end", None) if symbolic is not None else None),
        ))

    meta = dict(meta)
    meta["canonical_hit_count"] = len(hits)
    meta["symbolic_hit_count"] = len(symbolic_hits)
    meta["canonical_attack_keys"] = [f"{h.measure_index}:{h.offset_in_measure}" for h in hits]
    warnings = []
    if not hits:
        warnings.append("Canonical score-time recovery produced no usable attacks; symbolic MusicXML hits were retained.")
    return hits, warnings, meta
